INSERT INTO TB_TIPO_DOMINIO(DESCRICAO, CODIGO) VALUES ('Gênero', 'GENERO');
INSERT INTO TB_TIPO_DOMINIO(DESCRICAO, CODIGO) VALUES ('Tipo de telefone', 'TIPO_TELEFONE');
INSERT INTO TB_TIPO_DOMINIO(DESCRICAO, CODIGO) VALUES ('Tipo de anotação', 'TIPO_ANOTACAO');
INSERT INTO TB_TIPO_DOMINIO(DESCRICAO, CODIGO) VALUES ('Situação do tipo de anotação', 'SITUACAO_TIPO_ANOTACAO');

INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Masculino', 'MASCULINO', 1);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Feminino', 'FEMININO', 1);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Não binário', 'NAO_BINARIO', 1);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Residencial', 'RESIDENCIAL', 2);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Celular', 'CELULAR', 2);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Rascunho', 'RASCUNHO', 3);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Estudo', 'ESTUDO', 3);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Lembrete', 'LEMBRETE', 3);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Estudo em andamento', 'ESTUDO_ANDAMENTO', 4);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Estudo finalizado', 'ESTUDO_FINALIZADO', 4);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Rascunho em aberto', 'RASCUNHO_ABERTO', 4);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Rascunho finalizado', 'RASCUNHO_FINALIZADO', 4);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Lembrete em aberto', 'LEMBRETE_ABERTO', 4);
INSERT INTO TB_DOMINIO(DESCRICAO, CODIGO, ID_TIPO_DOMINIO) VALUES ('Lembrete finalizado', 'LEMBRETE_FINALIZADO', 4);

INSERT INTO TB_TELEFONE(NUMERO, DDD, DESCRICAO, ID_TIPO_TELEFONE, CREATED_AT) VALUES ('999999999', '11', 'telefone teste', 5, NOW());

INSERT INTO TB_USUARIO(NOME, EMAIL, CPF, RENDA, DATA_NASCIMENTO, QUANTIDADE_FILHOS, ID_TELEFONE, ID_GENERO, CREATED_AT) VALUES ('Nome teste', 'teste@email.com', '63801219003', 10000, '1990-03-06', 1, 1, 1, NOW());

INSERT INTO TB_ANOTACAO(TITULO, DESCRICAO, ID_USUARIO, ID_TIPO_ANOTACAO, ID_SITUACAO_TIPO_ANOTACAO, CREATED_AT) VALUES ('Rascunho', 'Rascunho....', 1, 6, 11, NOW());
