INSERT INTO TB_TIPO_DOMINIO (DESCRICAO, CODIGO) VALUES ('Gênero', 'GENERO');
INSERT INTO TB_TIPO_DOMINIO (DESCRICAO, CODIGO) VALUES ('Tipo de telefone', 'TIPO_TELEFONE');
INSERT INTO TB_TIPO_DOMINIO (DESCRICAO, CODIGO) VALUES ('Tipo de anotação', 'TIPO_ANOTACAO');
INSERT INTO TB_TIPO_DOMINIO (DESCRICAO, CODIGO) VALUES ('Situação do tipo de anotação', 'SITUACAO_TIPO_ANOTACAO');

INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Masculino', 'MASCULINO', 1);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Feminino', 'FEMININO', 1);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Não binário', 'NAO_BINARIO', 1);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Residencial', 'RESIDENCIAL', 2);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Celular', 'CELULAR', 2);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Rascunho', 'RASCUNHO', 3);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Estudo', 'ESTUDO', 3);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Lembrete', 'LEMBRETE', 3);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Estudo em andamento', 'ESTUDO_ANDAMENTO', 4);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Estudo finalizado', 'ESTUDO_FINALIZADO', 4);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Rascunho em aberto', 'RASCUNHO_ABERTO', 4);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Rascunho finalizado', 'RASCUNHO_FINALIZADO', 4);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Lembrete em aberto', 'LEMBRETE_ABERTO', 4);
INSERT INTO TB_DOMINIO (DESCRICAO, CODIGO, ID_TIPO_DOMINIO)  VALUES ('Lembrete finalizado', 'LEMBRETE_FINALIZADO', 4);