server:
  port: 8080

spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:postgresql://localhost:5000/usuarios?currentSchema=dev
    username: gabriel
    password: gabriel
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cache:
    type: redis
    host: localhost
    port: 6379

logging:
  level:
    org:
      flywaydb: DEBUG
    br.com.gabrielferreira.usuarios: TRACE

jwt:
  secret: ${JWT_SECRET:Zx{9b)YC>B#Q~';8zHy=6&jX/a$f*GbtwWZ6nm^UM5z<E6WA{c`?"BY_d~<bMF/q&xCQs3^{h`4fnX>wRa;D"c)#F5tgv7'HEA(W~;qRx/8J!=}
  expiration: ${JWT_EXPIRATION:3600000}