INSERT INTO TB_GENERO (DESCRICAO, CODIGO, CREATED_AT) VALUES ('Masculino', 'MASCULINO', NOW());
INSERT INTO TB_GENERO (DESCRICAO, CODIGO, CREATED_AT) VALUES ('Feminino', 'FEMININO', NOW());
INSERT INTO TB_GENERO (DESCRICAO, CODIGO, CREATED_AT) VALUES ('Não identificado', 'NAO_IDENTIFICADO', NOW());


INSERT INTO TB_TIPO_TELEFONE (DESCRICAO, CODIGO, CREATED_AT) VALUES ('Residencial', 'RESIDENCIAL', NOW());
INSERT INTO TB_TIPO_TELEFONE (DESCRICAO, CODIGO, CREATED_AT) VALUES ('Celular', 'CELULAR', NOW());

INSERT INTO TB_TELEFONE (NUMERO, DDD, DESCRICAO, ID_TIPO_TELEFONE, CREATED_AT) VALUES ('20927386', '65', 'Telefone do lucas', 1, NOW());
INSERT INTO TB_TELEFONE (NUMERO, DDD, DESCRICAO, ID_TIPO_TELEFONE, CREATED_AT) VALUES ('24357416', '81', 'Telefone do sebastiao', 1, NOW());
INSERT INTO TB_TELEFONE (NUMERO, DDD, DESCRICAO, ID_TIPO_TELEFONE, CREATED_AT) VALUES ('986421134', '82', 'Celular da mariah', 2, NOW());
INSERT INTO TB_TELEFONE (NUMERO, DDD, DESCRICAO, ID_TIPO_TELEFONE, CREATED_AT) VALUES ('980815185', '96', 'Celular da juliana', 2, NOW());

INSERT INTO TB_USUARIO (NOME, EMAIL, CPF, RENDA, DATA_NASCIMENTO, QUANTIDADE_FILHOS, ID_TELEFONE, ID_GENERO, CREATED_AT) VALUES ('Lucas Anthony Carlos Eduardo Assunção', 'lucas-assuncao91@arteche.com.br', '19827537733', 10000.00, '1964-02-13', 2, 1, 1, NOW());
INSERT INTO TB_USUARIO (NOME, EMAIL, CPF, RENDA, DATA_NASCIMENTO, QUANTIDADE_FILHOS, ID_TELEFONE, ID_GENERO, CREATED_AT) VALUES ('Sebastião Gabriel Monteiro', 'sebastiao_monteiro@grupoannaprado.com.br', '48678626810', 2500.00, '1973-03-12', 1, 2, 1, NOW());
INSERT INTO TB_USUARIO (NOME, EMAIL, CPF, RENDA, DATA_NASCIMENTO, QUANTIDADE_FILHOS, ID_TELEFONE, ID_GENERO, CREATED_AT) VALUES ('Mariah Luna Cardoso', 'mariah.luna.cardoso@asconnet.com.br', '28104715763', 5000.00, '1997-01-14', 0, 3, 2, NOW());
INSERT INTO TB_USUARIO (NOME, EMAIL, CPF, RENDA, DATA_NASCIMENTO, QUANTIDADE_FILHOS, ID_TELEFONE, ID_GENERO, CREATED_AT) VALUES ('Osvaldo André Thiago Rezende', 'osvaldo.andre.rezende@yahoo.com', '99763694507', 13000.00, '1990-01-23', 1, 4, 3, NOW());

